/**
 * Pre-build: generates static slugs for static export + Orama search index.
 */
import { writeFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, '..', 'content', 'docs');
const slugs = [];

function walkDir(dir, parentSlugs = []) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'meta.json') continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath, [...parentSlugs, entry.name]);
    } else if (entry.name.endsWith('.mdx')) {
      const name = entry.name.replace(/\.mdx$/, '');
      const slug = [...parentSlugs, name];
      slugs.push(slug);
      if (name === 'index' && parentSlugs.length > 0) {
        if (!slugs.some(s => s.length === parentSlugs.length && s.every((v, i) => v === parentSlugs[i]))) {
          slugs.push([...parentSlugs]);
        }
      }
    }
  }
}

walkDir(contentDir);
slugs.push([]);

// Deduplicate
const seen = new Set();
const unique = slugs.filter(s => {
  const key = s.join('/');
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

console.log(`Found ${unique.length} slugs`);

// Write static params for Next.js generateStaticParams
const outPath = join(__dirname, '..', 'lib', 'static-slugs.ts');
writeFileSync(outPath, `// Auto-generated by scripts/generate-params.mjs\nexport const staticSlugs: string[][] = ${JSON.stringify(unique, null, 2)};\n`);
console.log(`Written to lib/static-slugs.ts`);
